spring:
  application:
    name: bookmanagementsystem

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/book_management
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Flyway Configuration
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  # jOOQ Configuration
  jooq:
    sql-dialect: postgres
