/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.references


import com.bookmanagementsystem.jooq.tables.Author
import com.bookmanagementsystem.jooq.tables.AuthorBook
import com.bookmanagementsystem.jooq.tables.Book



/**
 * 著者情報を管理するテーブル
 */
val AUTHOR: Author = Author.AUTHOR

/**
 * 著者と書籍の中間テーブル（多対多対応）
 */
val AUTHOR_BOOK: AuthorBook = AuthorBook.AUTHOR_BOOK

/**
 * 書籍情報を管理するテーブル
 */
val BOOK: Book = Book.BOOK
