/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.references


import com.bookmanagementsystem.jooq.tables.Book



/**
 * 書籍情報を管理するテーブル
 */
val BOOK: Book = Book.BOOK
