/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.records


import com.bookmanagementsystem.jooq.tables.Author

import java.time.LocalDate

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 著者情報を管理するテーブル
 */
@Suppress("UNCHECKED_CAST")
open class AuthorRecord() : UpdatableRecordImpl<AuthorRecord>(Author.AUTHOR) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var birthDate: LocalDate?
        set(value): Unit = set(2, value)
        get(): LocalDate? = get(2) as LocalDate?

    open var version: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised AuthorRecord
     */
    constructor(id: Int? = null, name: String? = null, birthDate: LocalDate? = null, version: Int? = null): this() {
        this.id = id
        this.name = name
        this.birthDate = birthDate
        this.version = version
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    constructor(value: com.bookmanagementsystem.jooq.tables.pojos.Author?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.birthDate = value.birthDate
            this.version = value.version
            resetChangedOnNotNull()
        }
    }
}
