/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.records


import com.bookmanagementsystem.jooq.tables.Book

import java.math.BigDecimal

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * 書籍情報を管理するテーブル
 */
@Suppress("UNCHECKED_CAST")
open class BookRecord() : UpdatableRecordImpl<BookRecord>(Book.BOOK) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var price: BigDecimal?
        set(value): Unit = set(2, value)
        get(): BigDecimal? = get(2) as BigDecimal?

    open var publishStatus: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised BookRecord
     */
    constructor(id: Int? = null, title: String? = null, price: BigDecimal? = null, publishStatus: Int? = null): this() {
        this.id = id
        this.title = title
        this.price = price
        this.publishStatus = publishStatus
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BookRecord
     */
    constructor(value: com.bookmanagementsystem.jooq.tables.pojos.Book?): this() {
        if (value != null) {
            this.id = value.id
            this.title = value.title
            this.price = value.price
            this.publishStatus = value.publishStatus
            resetChangedOnNotNull()
        }
    }
}
