openapi: 3.0.3
info:
  title: Book Management System API
  description: 書籍管理システムのAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development Server

paths:
  /api/authors:
    post:
      tags:
        - Authors
      summary: 著者を作成する
      operationId: createAuthor
      description: |
        生年月日は現在より過去日付
      requestBody:
        description: 登録する著者の情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthorRequestModel'
      responses:
        '200':
          description: 著者の作成に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseModel'

components:
  schemas:
    CreateAuthorRequestModel:
      type: object
      description: 著者登録APIのリクエスト情報
      properties:
        name:
          type: string
          description: 著者名
          example: 太宰治
        birthDate:
          type: string
          format: date
          description: 生年月日
          example: "1909-06-19"
      required:
        - name

    AuthorResponseModel:
      type: object
      description: 著者のAPIで汎用的に使用するレスポンス情報
      properties:
        id:
          type: integer
          format: int32
          description: 著者ID
          example: 1
        name:
          type: string
          description: 著者名
          example: 太宰治
        birthDate:
          type: string
          format: date
          description: 生年月日
          example: "1909-06-19"
        books:
          type: array
          description: |
            著者の書籍一覧
            書籍がない場合は空配列
          items:
            $ref: '#/components/schemas/BookResponseModel'
      required:
        - id
        - name
        - books

    BookResponseModel:
      type: object
      description: 書籍のAPIで汎用的に使用するレスポンス情報
      properties:
        id:
          type: integer
          format: int32
          description: 書籍ID
          example: 1
        title:
          type: string
          description: 書籍タイトル
          example: 人間失格
        price:
          type: integer
          format: int64
          minimum: 0
          maximum: 9999999999
          description: 価格（円）(10桁)
          example: 1200
        status:
          $ref: '#/components/schemas/BookStatus'
      required:
        - id
        - title
        - price
        - status

    BookStatus:
      type: integer
      format: int32
      description: 出版ステータス
      enum:
        - 1
        - 2
      example: 1
      x-enum-varnames:
        - PUBLISHED
        - UNPUBLISHED