openapi: 3.0.3
info:
  title: Book Management System API
  description: 書籍管理システムのAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development Server

paths:
  /api/authors:
    post:
      tags:
        - Authors
      summary: 著者を作成する
      operationId: createAuthor
      description: |
        生年月日は現在より過去日付
      requestBody:
        description: 登録する著者の情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthorRequestModel'
      responses:
        '200':
          description: 著者の作成に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseModel'
  /api/authors/{id}:
    put:
      tags:
        - Authors
      summary: 著者を更新する
      operationId: updateAuthor
      description: |
        生年月日は現在より過去日付
      parameters:
        - name: id
          in: path
          required: true
          description: 更新する著者のID
          schema:
            type: integer
            format: int32
      requestBody:
        description: 更新する著者の情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthorRequestModel'
      responses:
        '200':
          description: 著者の更新に成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseModel'
        '404':
          description: 著者が見つからない場合
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponseModel'

components:
  schemas:
    CreateAuthorRequestModel:
      type: object
      description: 著者登録APIのリクエスト情報
      properties:
        name:
          type: string
          description: 著者名
          example: 太宰治
        birthDate:
          type: string
          format: date
          description: 生年月日
          x-field-extra-annotation: "@field:com.bookmanagementsystem.usecase.validation.PastOnly"
          example: "1909-06-19"
      required:
        - name

    UpdateAuthorRequestModel:
      type: object
      description: 著者更新APIのリクエスト情報
      properties:
        name:
          type: string
          description: 著者名
          example: 太宰治
        birthDate:
          type: string
          format: date
          description: 生年月日
          x-field-extra-annotation: "@field:com.bookmanagementsystem.usecase.validation.PastOnly"
          example: "1909-06-19"
      required:
        - name

    AuthorResponseModel:
      type: object
      description: 著者のAPIで汎用的に使用するレスポンス情報
      properties:
        id:
          type: integer
          format: int32
          description: 著者ID
          example: 1
        name:
          type: string
          description: 著者名
          example: 太宰治
        birthDate:
          type: string
          format: date
          description: 生年月日
          example: "1909-06-19"
      required:
        - id
        - name

    NotFoundErrorResponseModel:
      type: object
      description: 汎用的なエラーレスポンス
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorModel'

    ErrorModel:
      type: object
      description: エラー情報
      properties:
        code:
          type: string
          description: エラーコード
          example: "AUTHOR_NOT_FOUND"
        message:
          type: string
          description: エラーメッセージ
          example: "指定された著者が見つかりません"