/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.pojos


import java.io.Serializable


/**
 * 著者と書籍の中間テーブル（多対多対応）
 */
@Suppress("UNCHECKED_CAST")
data class AuthorBook(
    var authorId: Int? = null,
    var bookId: Int? = null,
    var version: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AuthorBook = other as AuthorBook
        if (this.authorId == null) {
            if (o.authorId != null)
                return false
        }
        else if (this.authorId != o.authorId)
            return false
        if (this.bookId == null) {
            if (o.bookId != null)
                return false
        }
        else if (this.bookId != o.bookId)
            return false
        if (this.version == null) {
            if (o.version != null)
                return false
        }
        else if (this.version != o.version)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.authorId == null) 0 else this.authorId.hashCode())
        result = prime * result + (if (this.bookId == null) 0 else this.bookId.hashCode())
        result = prime * result + (if (this.version == null) 0 else this.version.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AuthorBook (")

        sb.append(authorId)
        sb.append(", ").append(bookId)
        sb.append(", ").append(version)

        sb.append(")")
        return sb.toString()
    }
}
