/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDate


/**
 * 著者情報を管理するテーブル
 */
@Suppress("UNCHECKED_CAST")
data class Author(
    var id: Int? = null,
    var name: String? = null,
    var birthDate: LocalDate? = null,
    var version: Int? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Author = other as Author
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.birthDate == null) {
            if (o.birthDate != null)
                return false
        }
        else if (this.birthDate != o.birthDate)
            return false
        if (this.version == null) {
            if (o.version != null)
                return false
        }
        else if (this.version != o.version)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.birthDate == null) 0 else this.birthDate.hashCode())
        result = prime * result + (if (this.version == null) 0 else this.version.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Author (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(birthDate)
        sb.append(", ").append(version)

        sb.append(")")
        return sb.toString()
    }
}
