/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq.tables


import com.bookmanagementsystem.jooq.Public
import com.bookmanagementsystem.jooq.keys.AUTHOR_BOOK_PKEY
import com.bookmanagementsystem.jooq.keys.AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY
import com.bookmanagementsystem.jooq.keys.AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY
import com.bookmanagementsystem.jooq.tables.Author.AuthorPath
import com.bookmanagementsystem.jooq.tables.Book.BookPath
import com.bookmanagementsystem.jooq.tables.records.AuthorBookRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * 著者と書籍の中間テーブル（多対多対応）
 */
@Suppress("UNCHECKED_CAST")
open class AuthorBook(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuthorBookRecord>?,
    parentPath: InverseForeignKey<out Record, AuthorBookRecord>?,
    aliased: Table<AuthorBookRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuthorBookRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("著者と書籍の中間テーブル（多対多対応）"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.author_book</code>
         */
        val AUTHOR_BOOK: AuthorBook = AuthorBook()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthorBookRecord> = AuthorBookRecord::class.java

    /**
     * The column <code>public.author_book.author_id</code>. 著者ID（外部キー）
     */
    val AUTHOR_ID: TableField<AuthorBookRecord, Int?> = createField(DSL.name("author_id"), SQLDataType.INTEGER.nullable(false), this, "著者ID（外部キー）")

    /**
     * The column <code>public.author_book.book_id</code>. 書籍ID（外部キー）
     */
    val BOOK_ID: TableField<AuthorBookRecord, Int?> = createField(DSL.name("book_id"), SQLDataType.INTEGER.nullable(false), this, "書籍ID（外部キー）")

    /**
     * The column <code>public.author_book.version</code>. バージョン（楽観的ロック用）
     */
    val VERSION: TableField<AuthorBookRecord, Int?> = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "バージョン（楽観的ロック用）")

    private constructor(alias: Name, aliased: Table<AuthorBookRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuthorBookRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuthorBookRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.author_book</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.author_book</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.author_book</code> table reference
     */
    constructor(): this(DSL.name("author_book"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthorBookRecord>?, parentPath: InverseForeignKey<out Record, AuthorBookRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AUTHOR_BOOK, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AuthorBookPath : AuthorBook, Path<AuthorBookRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthorBookRecord>?, parentPath: InverseForeignKey<out Record, AuthorBookRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AuthorBookRecord>): super(alias, aliased)
        override fun `as`(alias: String): AuthorBookPath = AuthorBookPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AuthorBookPath = AuthorBookPath(alias, this)
        override fun `as`(alias: Table<*>): AuthorBookPath = AuthorBookPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthorBookRecord> = AUTHOR_BOOK_PKEY
    override fun getReferences(): List<ForeignKey<AuthorBookRecord, *>> = listOf(AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY, AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY)

    private lateinit var _author: AuthorPath

    /**
     * Get the implicit join path to the <code>public.author</code> table.
     */
    fun author(): AuthorPath {
        if (!this::_author.isInitialized)
            _author = AuthorPath(this, AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY, null)

        return _author;
    }

    val author: AuthorPath
        get(): AuthorPath = author()

    private lateinit var _book: BookPath

    /**
     * Get the implicit join path to the <code>public.book</code> table.
     */
    fun book(): BookPath {
        if (!this::_book.isInitialized)
            _book = BookPath(this, AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY, null)

        return _book;
    }

    val book: BookPath
        get(): BookPath = book()
    override fun `as`(alias: String): AuthorBook = AuthorBook(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthorBook = AuthorBook(alias, this)
    override fun `as`(alias: Table<*>): AuthorBook = AuthorBook(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthorBook = AuthorBook(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthorBook = AuthorBook(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthorBook = AuthorBook(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AuthorBook = AuthorBook(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AuthorBook = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AuthorBook = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AuthorBook = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AuthorBook = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AuthorBook = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AuthorBook = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AuthorBook = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AuthorBook = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AuthorBook = where(DSL.notExists(select))
}
