/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq


import com.bookmanagementsystem.jooq.tables.Author
import com.bookmanagementsystem.jooq.tables.AuthorBook
import com.bookmanagementsystem.jooq.tables.Book

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * 著者情報を管理するテーブル
     */
    val AUTHOR: Author get() = Author.AUTHOR

    /**
     * 著者と書籍の中間テーブル（多対多対応）
     */
    val AUTHOR_BOOK: AuthorBook get() = AuthorBook.AUTHOR_BOOK

    /**
     * 書籍情報を管理するテーブル
     */
    val BOOK: Book get() = Book.BOOK

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Author.AUTHOR,
        AuthorBook.AUTHOR_BOOK,
        Book.BOOK
    )
}
