/*
 * This file is generated by jOOQ.
 */
package com.bookmanagementsystem.jooq


import com.bookmanagementsystem.jooq.tables.Author
import com.bookmanagementsystem.jooq.tables.Book
import com.bookmanagementsystem.jooq.tables.BookAuthor

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * 著者情報を管理するテーブル
     */
    val AUTHOR: Author get() = Author.AUTHOR

    /**
     * 書籍情報を管理するテーブル
     */
    val BOOK: Book get() = Book.BOOK

    /**
     * 書籍と著者の中間テーブル（多対多対応）
     */
    val BOOK_AUTHOR: BookAuthor get() = BookAuthor.BOOK_AUTHOR

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Author.AUTHOR,
        Book.BOOK,
        BookAuthor.BOOK_AUTHOR
    )
}
